# Generated by Django 5.0.6 on 2026-03-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documento_propiedad', models.CharField(blank=True, max_length=250, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=15, null=True)),
                ('id_transportista', models.ForeignKey(db_column='id_transportista', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.transportista')),
            ],
            options={
                'db_table': 'tb_vehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_origen', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion_destino', models.CharField(blank=True, max_length=300, null=True)),
                ('latitud_origen', models.FloatField(blank=True, null=True)),
                ('longitud_origen', models.FloatField(blank=True, null=True)),
                ('latitud_destino', models.FloatField(blank=True, null=True)),
                ('longitud_destino', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('peso_total_kg', models.FloatField(blank=True, null=True)),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_por_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.compra')),
                ('id_transportista', models.ForeignKey(blank=True, db_column='id_transportista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.transportista')),
                ('id_vehiculo', models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='envios.vehiculo')),
            ],
            options={
                'db_table': 'tb_envios',
                'managed': True,
            },
        ),
    ]
