# Generated by Django 5.0.6 on 2026-04-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.compra'),
        ),
        migrations.AddField(
            model_name='envio',
            name='id_transportista',
            field=models.ForeignKey(blank=True, db_column='id_transportista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.transportista'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id_transportista',
            field=models.ForeignKey(db_column='id_transportista', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.transportista'),
        ),
        migrations.AddField(
            model_name='envio',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='envios.vehiculo'),
        ),
    ]
