# Generated by Django 6.0.2 on 2026-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20),
        ),
    ]
