# Generated by Django 5.0.6 on 2026-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='documento_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/'),
        ),
    ]
