# Generated by Django 5.0.6 on 2026-04-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_initial'),
        ('envios', '0002_vehiculo_estado'),
    ]

    operations = [
    ]
