# Generated by Django 6.0.6 on 2026-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_vehiculo_documento_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='foto_carga',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_carga/'),
        ),
        migrations.AddField(
            model_name='envio',
            name='foto_descarga',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_descarga/'),
        ),
    ]
