# Generated by Django 5.0.6 on 2026-06-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_envio_foto_carga_envio_foto_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('ACTIVO', 'Activo'), ('RECHAZADO', 'Rechazado'), ('SUSPENDIDO', 'Suspendido'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20),
        ),
    ]
