# Generated by Django 5.0.6 on 2026-03-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente')),
            ],
            options={
                'db_table': 'tb_compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.compra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
            ],
            options={
                'db_table': 'tb_detalles_compra',
                'managed': True,
            },
        ),
    ]
