# Generated by Django 5.0.6 on 2026-04-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='carrito', max_length=20),
        ),
    ]
