# Generated by Django 5.0.6 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_hora_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
