# Generated by Django 5.0.6 on 2026-04-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_compra_fecha_hora_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('ref_epayco', models.CharField(max_length=100, unique=True)),
                ('ref_interna', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('mensaje_respuesta', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('datos_raw', models.JSONField(default=dict)),
                ('id_compra', models.OneToOneField(db_column='id_compra', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.compra')),
            ],
            options={
                'db_table': 'tb_pagos',
                'managed': True,
            },
        ),
    ]
