# Generated by Django 5.0.6 on 2026-04-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_compra_estado_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
