# Generated by Django 5.0.6 on 2026-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_delete_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='latitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='longitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallescompra',
            name='distancia_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
