# Generated by Django 5.0.6 on 2026-03-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
