# Generated by Django 5.0.6 on 2026-04-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('rol', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'tb_administradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo_asesoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_asesores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('preferencias', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tb_clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo_cultivo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_productores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('zonas_entrega', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tb_transportistas',
                'managed': True,
            },
        ),
    ]
