# Generated by Django 5.0.6 on 2026-06-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_alter_vehiculo_estado'),
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SOLICITUD_VEHICULO', 'Solicitud de vehículo'), ('APROBACION_VEHICULO', 'Vehículo aprobado'), ('RECHAZO_VEHICULO', 'Vehículo rechazado')], max_length=50)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(db_column='destino', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
                ('id_vehiculo', models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envios.vehiculo')),
            ],
            options={
                'db_table': 'tb_notificaciones',
                'managed': True,
            },
        ),
    ]
