# Generated by Django 6.0.2 on 2026-03-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena_usuario',
        ),
    ]
