# Generated by Django 5.0.6 on 2026-04-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='privilegios_admin',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario'),
        ),
    ]
