# Generated by Django 5.0.6 on 2026-03-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_categorias_productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id_finca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_finca', models.CharField(blank=True, max_length=200, null=True)),
                ('certificado_bpa', models.CharField(blank=True, db_column='certificado_BPA', max_length=200, null=True)),
                ('certificado_mirfe', models.CharField(blank=True, db_column='certificado_MIRFE', max_length=200, null=True)),
                ('certificado_mipe', models.CharField(blank=True, db_column='certificado_MIPE', max_length=200, null=True)),
                ('registro_ica', models.CharField(blank=True, db_column='registro_ICA', max_length=200, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.productor')),
            ],
            options={
                'db_table': 'tb_fincas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_calificacion', models.ForeignKey(blank=True, db_column='id_calificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calificaciones.calificacion')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoriaproducto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.productor')),
            ],
            options={
                'db_table': 'tb_productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(upload_to='productos/')),
                ('es_principal', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenProducto', to='productos.producto')),
            ],
            options={
                'db_table': 'tb_imagenes_productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoFinca',
            fields=[
                ('id_producto_finca', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_produccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('id_finca', models.ForeignKey(db_column='id_finca', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_finca', to='productos.finca')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fincas', to='productos.producto')),
            ],
            options={
                'db_table': 'tb_productos_fincas',
                'managed': True,
            },
        ),
    ]
