# Generated by Django 5.0.6 on 2026-03-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenProducto', to='productos.producto'),
        ),
    ]
