# Generated by Django 6.0.6 on 2026-06-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoriaproducto')),
            ],
            options={
                'db_table': 'tb_tipos_producto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.tipoproducto'),
        ),
        migrations.CreateModel(
            name='VariedadProducto',
            fields=[
                ('id_variedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='productos.tipoproducto')),
            ],
            options={
                'db_table': 'tb_variedades_producto',
                'managed': True,
                'unique_together': {('id_tipo', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_variedad',
            field=models.ForeignKey(blank=True, db_column='id_variedad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.variedadproducto'),
        ),
    ]
