# Generated by Django 5.0.6 on 2026-03-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_imagenesproducto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productofinca',
            name='id_finca',
            field=models.ForeignKey(db_column='id_finca', on_delete=django.db.models.deletion.CASCADE, related_name='productos_finca', to='productos.finca'),
        ),
        migrations.AlterField(
            model_name='productofinca',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='productos.producto'),
        ),
    ]
