# Generated by Django 5.0.6 on 2026-04-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productofinca_id_finca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_calificacion',
        ),
    ]
