# Generated by Django 5.0.6 on 2026-04-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_producto', models.IntegerField(blank=True, null=True)),
                ('puntaje_productor', models.IntegerField(blank=True, null=True)),
                ('puntaje_transportista', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='pedidos.compra')),
            ],
            options={
                'db_table': 'tb_calificacion',
            },
        ),
    ]
